{attribute 'qualified_only'}
VAR_GLOBAL
	// Sensors is a Global Variable List object to reference all sensor function blocks.
	
	BagFull: ReflectiveSensor;
	BagOpen: ReflectiveSensor;
	BagLabel: ReflectiveSensor;
	DoorClosed: ProximitySensor;
	DoorLocked: ProximitySensor;
	HeatSealClosed: ProximitySensor;
	HeatSealOpen: ProximitySensor;
	HopperMaximum: ReflectiveSensor;
	HopperMinimum: ReflectiveSensor;
	KickerBlocked: ReflectiveSensor;
	KickerDown: ProximitySensor;
	KickerUp: ProximitySensor;
END_VAR
